name: CI

on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  IMAGE_NAME: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/juice-shop


jobs:
  build_image:
    runs-on: [self-hosted, juice-shop]
    steps:
      - uses: actions/checkout@v4
      - name: Set IMAGE_NAME
        run: echo "IMAGE_NAME=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/juice-shop" >> $GITHUB_ENV
      - name: Log in to ECR
        run: aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - run: docker build -t $IMAGE_NAME:${{ github.sha }} -t $IMAGE_NAME:latest .
      - run: docker push $IMAGE_NAME:${{ github.sha }}
      - run: docker push $IMAGE_NAME:latest

  deploy_image:
    runs-on: ubuntu-latest
    container: 
      image: amazon/aws-cli
      options: --entrypoint ""
    steps:
    - run: |
        IMAGE_NAME="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/juice-shop"
        LOG_IN_CMD="export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID; \
        export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY; \
        export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION; aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com  "
        COMMAND_TO_EXECUTE="docker pull $IMAGE_NAME:latest && \
        (docker stop juice-shop 2>/dev/null || true) && \
        (docker rm juice-shop 2>/dev/null || true)  && \
        (docker run -d --name juice-shop -p 3000:3000 $IMAGE_NAME:latest)"
        COMMAND_ID=$(aws ssm send-command \
        --instance-id "i-0686d100902fa84fc" \
        --document-name "AWS-RunShellScript" \
        --parameters commands="[$LOG_IN_CMD, $COMMAND_TO_EXECUTE]" \
        --query "Command.CommandId" \
        --output text)
        sleep 15
        aws ssm get-command-invocation \
        --command-id "$COMMAND_ID" \
        --instance-id "i-0686d100902fa84fc"