name: CI

on: [push]

env:
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  IMAGE_NAME: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/juice-shop


jobs:
  build_image:
    runs-on: [self-hosted, juice-shop]
    steps:
      - uses: actions/checkout@v4
      - name: Set IMAGE_NAME
        run: echo "IMAGE_NAME=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/juice-shop" >> $GITHUB_ENV
      - name: Log in to ECR
        run: aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - run: docker build -t $IMAGE_NAME:${{ github.sha }} -t $IMAGE_NAME:latest .
      - run: docker push $IMAGE_NAME:${{ github.sha }}
      - run: docker push $IMAGE_NAME:latest

  deploy_image:
    runs-on: [self-hosted, juice-shop]
    needs: build_image
    steps:
    - name: Deploy via SSM
      run: |
        IMAGE_NAME="${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_DEFAULT_REGION }}.amazonaws.com/juice-shop"
        LOG_IN_CMD="aws ecr get-login-password --region ${{ vars.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_DEFAULT_REGION }}.amazonaws.com"
        COMMANDS_TO_EXECUTE="docker pull $IMAGE_NAME:latest && (docker stop juice-shop || true) && (docker rm juice-shop || true) && docker run -d --name juice-shop -p 3000:3000 $IMAGE_NAME:latest"
        cat <<EOF > ssm_parameters.json
        {
          "commands": [
            "$LOG_IN_CMD",
            "$COMMANDS_TO_EXECUTE"
          ]
        }
        EOF
        COMMAND_ID=$(aws ssm send-command \
          --instance-ids "i-0a52a49f7d6868465" \
          --document-name "AWS-RunShellScript" \
          --parameters file://ssm_parameters.json \
          --query "Command.CommandId" \
          --output text)
        echo "Sent SSM Command ID: $COMMAND_ID"
        sleep 15
        aws ssm get-command-invocation \
          --command-id "$COMMAND_ID" \
          --instance-id "i-0a52a49f7d6868465"
